UnitOfWork/Models/ProductOptions.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using UnitOfWork.Data.Base;

namespace UnitOfWork.Models
{
    public class ProductOptions : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        [DisplayName("Option 1")]
        public string? option11 { get; set; }
        [DisplayName("Option 2")]
        public string? option22 { get; set; }
        [DisplayName("Option 3")]
        public string? option33 { get; set; }
        [DisplayName("Option 4")]
        public string? option44 { get; set; }
        [DisplayName("Option 5")]
        public string? option55 { get; set; }
        [DisplayName("Option 6")]
        public string? option66 { get; set; }

    }
}

UnitOfWork/Areas/Myadmin/Controllers/ProductOptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UnitOfWork.Data;
using UnitOfWork.Models;
using static UnitOfWork.Helper;

namespace UnitOfWork.Areas.Myadmin.Controllers
{
    [Area("Myadmin")]
    [Authorize]
    public class ProductOptionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductOptionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Myadmin/ProductOptions
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProductOptions.ToListAsync());
        }



        // GET: Myadmin/ProductOptions/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null || _context.ProductOptions == null)
        //    {
        //        return NotFound();
        //    }

        //    var productOptions = await _context.ProductOptions
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (productOptions == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(productOptions);
        //}

        // GET: Myadmin/ProductOptions/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}


        [NoDirectAccess]
        public async Task<IActionResult> AddOEdit(int id = 0)
        {
            if (id == 0)
                return View(new ProductOptions());
            else
            {
                var productOpt = await _context.ProductOptions.FindAsync(id);
                if (productOpt == null)
                {
                    return NotFound();
                }
                return View(productOpt);
            }
        }

        // POST: Myadmin/ProductOptions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,option11,option22,option33,option44,option55,option66")] ProductOptions productOptions)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(productOptions);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(productOptions);
        //}

        //GET: Myadmin/ProductOptions/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null || _context.ProductOptions == null)
        //    {
        //        return NotFound();
        //    }

        //    var productOptions = await _context.ProductOptions.FindAsync(id);
        //    if (productOptions == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(productOptions);
        //}

        // POST: Myadmin/ProductOptions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOEdit(int id, [Bind("Id,option11,option22,option33,option44,option55,option66")] ProductOptions productOptions)
        {
            if (ModelState.IsValid)
            {
                //Insert
                if (id == 0)
                {
                    //transactionModel.Date = DateTime.Now;
                    _context.Add(productOptions);
                    await _context.SaveChangesAsync();

                }
                //Update
                else
                {
                    try
                    {
                        _context.Update(productOptions);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ProductOptionsExists(productOptions.Id))
                        { return NotFound(); }
                        else
                        { throw; }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.ProductOptions.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOEdit", productOptions) });

        }

        // GET: Myadmin/ProductOptions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProductOptions == null)
            {
                return NotFound();
            }

            var productOptions = await _context.ProductOptions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productOptions == null)
            {
                return NotFound();
            }

            return View(productOptions);
        }

        // POST: Myadmin/ProductOptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProductOptions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ProductOptions'  is null.");
            }
            var productOptions = await _context.ProductOptions.FindAsync(id);
            if (productOptions != null)
            {
                _context.ProductOptions.Remove(productOptions);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductOptionsExists(int id)
        {
          return (_context.ProductOptions?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

UnitOfWork/Controllers/ProductOptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UnitOfWork.Data;
using UnitOfWork.Models;

namespace UnitOfWork.Controllers
{
    public class ProductOptionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductOptionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ProductOptions
        public async Task<IActionResult> Index()
        {
              return _context.ProductOptions != null ? 
                          View(await _context.ProductOptions.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.ProductOptions'  is null.");
        }





        // GET: ProductOptions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProductOptions == null)
            {
                return NotFound();
            }

            var productOptions = await _context.ProductOptions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productOptions == null)
            {
                return NotFound();
            }

            return View(productOptions);
        }

        // GET: ProductOptions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProductOptions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,option11,option22,option33,option44,option55,option66")] ProductOptions productOptions)
        {
            if (ModelState.IsValid)
            {
                _context.Add(productOptions);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productOptions);
        }

        public async Task<IActionResult> AddOEdit(int Id =0)
        {
            if (Id == 0)
            {
                return View(new ProductOptions());
            }
            else
            {
             var productOptions = await _context.ProductOptions.FindAsync(Id);

            if (productOptions == null)
            {
                return NotFound();
            }
            return View(productOptions);
            }

            
            
        }

        // GET: ProductOptions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProductOptions == null)
            {
                return NotFound();
            }

            var productOptions = await _context.ProductOptions.FindAsync(id);
            if (productOptions == null)
            {
                return NotFound();
            }
            return View(productOptions);
        }

        // POST: ProductOptions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,option11,option22,option33,option44,option55,option66")] ProductOptions productOptions)
        {
            if (id != productOptions.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productOptions);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductOptionsExists(productOptions.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productOptions);
        }

        // GET: ProductOptions/Delete/5
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null || _context.ProductOptions == null)
            {
                return NotFound();
            }

            var productOptions = await _context.ProductOptions
                .FirstOrDefaultAsync(m => m.Id == Id);
            if (productOptions == null)
            {
                return NotFound();
            }

            return View(productOptions);
        }

        // POST: ProductOptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            if (_context.ProductOptions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ProductOptions'  is null.");
            }
            var productOptions = await _context.ProductOptions.FindAsync(Id);
            if (productOptions != null)
            {
                _context.ProductOptions.Remove(productOptions);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductOptionsExists(int Id)
        {
          return (_context.ProductOptions?.Any(e => e.Id == Id)).GetValueOrDefault();
        }
    }
}

UnitOfWork/Areas/Myadmin/Views/ProductOptions/AddOEdit.cshtml
@model UnitOfWork.Models.ProductOptions

@{
    ViewData["Title"] = "Create";
    //Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<form asp-area="Myadmin" asp-action="AddOEdit" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="row">
              <div class="col-md-6">
                    
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="option11" class="control-label"></label>
                            <input asp-for="option11" class="form-control" />
                            <span asp-validation-for="option11" class="text-danger"></span>
                        </div>
                        </div>
                      <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="option22" class="control-label"></label>
                            <input asp-for="option22" class="form-control" />
                            <span asp-validation-for="option22" class="text-danger"></span>
                        </div>
                     </div>
                
          </div>

                <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="option33" class="control-label"></label>
            <input asp-for="option33" class="form-control" />
            <span asp-validation-for="option33" class="text-danger"></span>
        </div>
                    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="option44" class="control-label"></label>
            <input asp-for="option44" class="form-control" />
            <span asp-validation-for="option44" class="text-danger"></span>
        </div>
                    </div>
                </div>


<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="option55" class="control-label"></label>
            <input asp-for="option55" class="form-control" />
            <span asp-validation-for="option55" class="text-danger"></span>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="option66" class="control-label"></label>
            <input asp-for="option66" class="form-control" />
            <span asp-validation-for="option66" class="text-danger"></span>
        </div>
    </div>
</div>






           
           
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>

UnitOfWork/Areas/Myadmin/Views/ProductOptions/Edit.cshtml
@model UnitOfWork.Models.ProductOptions

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>ProductOptions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="option11" class="control-label"></label>
                <input asp-for="option11" class="form-control" />
                <span asp-validation-for="option11" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="option22" class="control-label"></label>
                <input asp-for="option22" class="form-control" />
                <span asp-validation-for="option22" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="option33" class="control-label"></label>
                <input asp-for="option33" class="form-control" />
                <span asp-validation-for="option33" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="option44" class="control-label"></label>
                <input asp-for="option44" class="form-control" />
                <span asp-validation-for="option44" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="option55" class="control-label"></label>
                <input asp-for="option55" class="form-control" />
                <span asp-validation-for="option55" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="option66" class="control-label"></label>
                <input asp-for="option66" class="form-control" />
                <span asp-validation-for="option66" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UnitOfWork/Areas/Myadmin/Views/ProductOptions/Index.cshtml
@model IEnumerable<UnitOfWork.Models.ProductOptions>

@using X.PagedList.Mvc.Core; <!--import to get HTML Helper-->
@using X.PagedList;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    body {
        font-size: 12px;
    }

    .table thead th {
        color: #000000;
        vertical-align: bottom;
        border-bottom: 1px solid #dee2e6;
    }
</style>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

<div class="modal" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <!--
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>-->
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

UnitOfWork/Areas/Myadmin/Views/ProductOptions/_ViewAll.cshtml
@model IEnumerable<UnitOfWork.Models.ProductOptions>
@using X.PagedList.Mvc.Core; <!--import to get HTML Helper-->
@using X.PagedList;
@{
    ViewData["Title"] = "Index";
   
}

<style>
    body {
        font-size: 12px;
    }

    .table thead th {
        color: #000000;
        vertical-align: bottom;
        border-bottom: 1px solid #dee2e6;
    }
</style>

<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                @Html.DisplayNameFor(model => model.option11)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.option22)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.option33)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.option44)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.option55)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.option66)
            </th>
            <th>
                
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            // csharp code block
            // everything in here is code, don't have to use @
            var counter = 0;
        }
@foreach (var item in Model) {
            counter++;
        <tr>
                <td>
                    @counter
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.option11)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.option22)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.option33)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.option44)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.option55)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.option66)
            </td>
            <td>
                     <a onclick="showInPopup('@Url.Action("AddOEdit","ProductOptions",new {id=item.Id},Context.Request.Scheme)','Update Item')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i> Edit</a>
                              
             </td>
        </tr>
}
    </tbody>
</table>